name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@master
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
