name: Upload Pre-release

on:
  workflow_run:
    workflows: Build
    branches: main
    types:
      - completed

jobs:
  Upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download Packages
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: build.yml
          commit: ${{github.sha}}

      - name: Prepare the Packages
        run: |
          cd ${{github.workspace}}/UnityAssetReplacer-win-x86-${{github.sha}}.zip/ && zip -9 UnityAssetReplacer-win-x86-prerelease.zip ./*
          cd ${{github.workspace}}/UnityAssetReplacer-win-x64-${{github.sha}}.zip/ && zip -9 UnityAssetReplacer-win-x64-prerelease.zip ./*
          cd ${{github.workspace}}/UnityAssetReplacer-linux-x64-${{github.sha}}.zip/ && zip -9 UnityAssetReplacer-linux-x64-prerelease.zip ./*
          cd ${{github.workspace}}/UnityAssetReplacer-osx-x64-${{github.sha}}.zip/ && zip -9 UnityAssetReplacer-osx-x64-prerelease.zip ./*

      - name: Upload Pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: latest
          title: Development Build
          files: |
            UnityAssetReplacer-win-x86-${{github.sha}}.zip/UnityAssetReplacer-win-x86-prerelease.zip
            UnityAssetReplacer-win-x64-${{github.sha}}.zip/UnityAssetReplacer-win-x64-prerelease.zip
            UnityAssetReplacer-linux-x64-${{github.sha}}.zip/UnityAssetReplacer-linux-x64-prerelease.zip
            UnityAssetReplacer-osx-x64-${{github.sha}}.zip/UnityAssetReplacer-osx-x64-prerelease.zip
